steps:
  - name: 'eclipse-temurin:25-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update -qq && apt-get install -y -qq git
        ./gradlew :server:build -PexcludeMobile=true -x test --build-cache --no-daemon --quiet

options:
  logging: CLOUD_LOGGING_ONLY