steps:
  - name: 'gcr.io/cloud-builders/gradle:9.2.1-jdk25'
    args:
        [':server:build', '-PexcludeMobile=true', '-x test', '--build-cache', '--no-daemon', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY