package com.slovy.slovymovyapp.analytics

enum class AnalyticsEvent {
    DOWNLOAD_DICTIONARY_CLICK,
    DOWNLOAD_CANCEL_CLICK,
    WELCOME_SCREEN_CLICK,
    DOWNLOAD_LATER_CLICK,
    SETTINGS_DOWNLOAD_DICTIONARY_CLICK,
    SETTINGS_DOWNLOAD_TRANSLATION_CLICK,
    SETTINGS_DOWNLOAD_CANCEL_CLICK,
    LANG_TO_TRANSLATE_SELECTED,
    LANG_TO_LEARN_SELECTED,
    LANG_TO_LEARN_NOT_SELECTED,
    FAVORITES_REMOVE,
    FAVORITES_SAVE,
    FAVORITES_WORD_SHOW,
    FAVORITES_SEARCH_QUERY,
    WORD_PLAY_CLICK,
    WORD_STOP_PLAY_CLICK,
    WORD_SEARCH_RESULT_SHOW,
    WORD_SEARCH_SUGGESTION_CLICK,
    SETTINGS_TEST_VOICE_CLICK,
    SETTINGS_OPEN_SYSTEM_SETTINGS_CLICK,
    SETTINGS_VOICE_DISABLE_CLICK,
    SETTINGS_VOICE_ENABLE_CLICK,
    STUDY_START_SESSION,
    STUDY_CANCEL_SESSION,
    STUDY_END_SESSION,
    FAVORITES_STUDY_DUE_CLICK,
    FAVORITES_STUDY_DONE_REVIEW_MORE_CLICK,
    FAVORITES_STUDY_DONE_STUDY_NEW_CLICK,
    STATS_SCREEN_OPEN,
    LEARNING_INTAKE_RUN,
    STUDY_CARD_GRADED,
    STUDY_HINT_REVEALED,
    WORD_SEARCH_QUERY,
    WORD_DETAIL_OPEN,
    DOWNLOAD_COMPLETED,
    DOWNLOAD_FAILED,
    DATA_VERSION_MISMATCH,
    TTS_PLAY_FAILED,
    SETTING_CHANGED,
    REVIEW_APP_CLICK
}

expect object Analytics {
    /**
     * Routes [logEvent] calls. Defaults to [NoOpAnalyticsLogger] so tests
     * don't crash on platforms whose backing SDK isn't initialised; the
     * production entry point (e.g. MainActivity) installs the real logger.
     */
    var logger: AnalyticsLogger

    fun logEvent(event: AnalyticsEvent, params: Map<String, Any> = emptyMap())

    fun setUserProperty(name: String, value: String?)
}
