package com.slovy.slovymovyapp.analytics

enum class AnalyticsEvent {
    DOWNLOAD_DICTIONARY_CLICK,
    WELCOME_SCREEN_CLICK,
    DOWNLOAD_LATER_CLICK,
    LANG_TO_TRANSLATE_SELECTED,
    LANG_TO_LEARN_SELECTED,
    LANG_TO_LEARN_NOT_SELECTED,
    FAVOURITES_REMOVE,
    FAVOURITES_SAVE,
    FAVORITES_WORD_SHOW,
    WORD_DETAILS_FAVOURITES_REMOVE,
    WORD_DETAILS_FAVOURITES_SAVE,
    WORD_PLAY_CLICK,
    WORD_STOP_PLAY_CLICK,
    WORD_SEARCH_RESULT_SHOW,
    WORD_SEARCH_SUGGESTION_CLICK,
    SETTINGS_TEST_VOICE_CLICK,
    SETTINGS_OPEN_SYSTEM_SETTINGS_CLICK,
    SETTINGS_VOICE_DISABLE_CLICK,
    SETTINGS_VOICE_ENABLE_CLICK,
}

expect object Analytics {
    fun logEvent(event: AnalyticsEvent, params: Map<String, String> = emptyMap())
}
