import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.ValueSource
import org.gradle.api.provider.ValueSourceParameters
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.ByteArrayOutputStream
import javax.inject.Inject

abstract class GitCommitCountValueSource : ValueSource<Int, ValueSourceParameters.None> {
    @get:Inject
    abstract val execOperations: ExecOperations

    override fun obtain(): Int {
        val out = ByteArrayOutputStream()
        execOperations.exec {
            commandLine("git", "rev-list", "--count", "HEAD")
            standardOutput = out
        }
        return out.toString(Charsets.UTF_8).trim().toInt()
    }
}

abstract class WriteAppVersionTask : DefaultTask() {
    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val packageDir = outputDir.get().asFile.resolve("com/slovy/slovymovyapp/generated")
        packageDir.mkdirs()
        packageDir.resolve("AppVersion.kt").writeText(
            """
            package com.slovy.slovymovyapp.generated

            internal object AppVersion {
                const val NAME: String = "${versionName.get()}"
                const val CODE: Int = ${versionCode.get()}
            }

            """.trimIndent()
        )
    }
}

abstract class WriteIosVersionXcconfigTask : DefaultTask() {
    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun write() {
        outputFile.get().asFile.apply { parentFile.mkdirs() }.writeText(
            """
            // Generated. Do not edit. Regenerated by Gradle :composeApp:generateIosVersionXcconfig.
            CURRENT_PROJECT_VERSION = ${versionCode.get()}
            MARKETING_VERSION = ${versionName.get()}

            """.trimIndent()
        )
    }
}
